server:
  port: 8080
spring:
  application:
    name: YIIU
    index: 1
  resources:
    static-locations:
    - classpath:/${site.theme}/static/
    - file:./views/${site.theme}/static/
  freemarker:
    template-loader-path:
    - classpath:/${site.theme}/templates/
    - file:./views/${site.theme}/templates/
    cache: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./yiiu.sqlite
#  datasource:
#    url: jdbc:mysql://localhost/yiiu?useSSL=false&characterEncoding=utf8
#    username: root
#    password: 123123
  jpa:
#    database: mysql
    database-platform: co.yiiu.core.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ./indexes
      hibernate.search.lucene_version: LUCENE_CURRENT
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.qq.com
    username: xxoo@qq.com
    password: # 这里的密码是QQ邮箱的授权码
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  http:
    multipart:
      max-file-size: 2MB
security:
  oauth2:
    client:
      client-id:
      client-secret:
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      registered-redirect-uri: ${site.baseUrl}/github_login
      use-current-uri: false
    resource:
      userInfoUri: https://api.github.com/user
    sso:
      login-path: /github_login

site:
  name: YIIU
  intro: <h5>属于Java语言的bbs</h5><p>在这里，您可以提问，回答，分享，诉说，这是个属于Java程序员的社区，欢迎您的加入！</p>
  baseUrl: http://localhost:8080/ # 不要忘了后面的 '/'
  staticUrl: http://localhost:8080/static/images/upload/
  pageSize: 20
  uploadPath: ./views/${site.theme}/static/images/upload/
  theme: default
  search: true
  attempts: 5
  attemptsWaitTime: 15
  maxCreateTopic: 10
  createTopicScore: -10  # 创建主题变化的积分
  createReplyScore : -5  # 创建回复变化的积分
  userUploadSpaceSize: 50 # 单位MB
  score: 2000 # 用户注册后初始积分
  loginPoints: 2 # 登录点，最多2个位置登录，第三个登录点会覆盖第一个
  GA: #Google Analytics ID
  googleZZ: # google站长meta标签content值
  baiduTJ: # 百度统计ID
  baiduZZ: # 百度站长meta标签content值
  ssl: false # 网站重写向是否转到https上，默认是否，如果你网站开启了https，请把这个设置为true
  newUserRole: user # 这里跟data.yml里的 _roles 里配置的角色名字要一
  cookie:
    domain: localhost
    attendanceMaxAge: 86400
    attendanceName: attendance
    rememberMeExpireDay: 30 # 记住我30天
  mail:
    subject: 注册验证码 - ${site.name}
    content: |
          <p>您好</p>
          <p>&nbsp;&nbsp;您的验证码为 <span style='color: red;'>${genCode}</span> , 请在10分钟内使用！</p><br>
          <small>本邮件为系统发出，请不要回复</small>

score:
  template:
    dailySign: 每日签到获得${scoreLog.changeScore}积分
    createTopic: 发表主题[<a href="/topic/${topic.id}" target="_blank">${topic.title?html}</a>],扣减${scoreLog.changeScore}积分
    replyTopic: 回复主题[<a href="/topic/${topic.id}"  target="_blank">${topic.title?html}</a>],扣减${scoreLog.changeScore}积分
    register: 用户注册奖励${scoreLog.changeScore}积分