spring:
  banner:
    location: file:./banner.txt

site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://localhost:3306/pybbs?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  datasource_username: root
  datasource_password:
